name = "portfolio-app"
compatibility_date = "2025-05-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build"

[[rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.mjs"]

[env.production]
name = "portfolio-app"

[env.production.vars]
NODE_ENV = "production"
NITRO_PRESET = "cloudflare-pages"
